Add enviroment info on build-and-deploy

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -5,7 +5,7 @@ on:
     branches: [ "main" ]
   workflow_dispatch:
 
-# Required permissions for deploy-pages (id token + pages write)
+# Required permissions for deploy-pages (id token + all write)
 permissions:
   contents: write
   pages: write
@@ -14,6 +14,7 @@ permissions:
 jobs:
   build:
     runs-on: ubuntu-latest
+    environment: production
 
     steps:
       - name: Checkout
@@ -38,6 +39,15 @@ jobs:
           NG_APP_PUBLIC_FIREBASE_APP_ID=${{ secrets.NG_APP_PUBLIC_FIREBASE_APP_ID }}
           EOF
         shell: bash
+
+      - name: Check environment secrets
+        run: |
+          if [ -z "${{ secrets.NG_APP_PUBLIC_FIREBASE_API_KEY }}" ]; then
+            echo "MISSING: NG_APP_PUBLIC_FIREBASE_API_KEY"
+            exit 1
+          else
+            echo "FOUND: NG_APP_PUBLIC_FIREBASE_API_KEY"
+          fi
 
       - name: Build project
         run: npm run build
